version: '3.4'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ${CONFIG}/nginx/data:/data
      - ${CONFIG}/nginx/letsencrypt:/etc/letsencrypt

  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ${CONFIG}/nginx/data/mysql:/var/lib/mysql

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
        - net_admin
    volumes:
        - ${CONFIG}/vpn:/vpn
    environment:
        - VPN_AUTH=${VPN_AUTH}
        - TZ=${TZ}
    ports:
        - 8112:8112 #deluge
        - 8080:8080 #sabnzbd
    restart: unless-stopped

  deluge: #8112
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/deluge:/config
      - ${DATA}/media:/data
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DATA}/media:/data
    restart: unless-stopped

  jackett: #9117
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/jackett:/config
      - ${DATA}/downloads/torrent-blackhole:/downloads
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  radarr: #7878
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/media:/data
      - ${CONFIG}/radarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  sonarr: #8989
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA}/media:/data
      - ${CONFIG}/sonarr:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  bazarr: #6767
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${DATA}/media:/data
    restart: unless-stopped

  flaresolverr: #8191
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: unless-stopped 

  plex: #32400
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ${CONFIG}/plex:/config
      - ${DATA}/media/tv:/data/tv
      - ${DATA}/media/movies:/data/movies
      - ${DATA}/media/music:/data/music
    environment:
      - TZ=${TZ}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PLEX_CLAIM=${PLEX_TOKEN}
      - ADVERTISE_IP=plex.${DOMAIN}
    restart: unless-stopped

  tautulli: #8181
    image: linuxserver/tautulli
    container_name: tautulli
    volumes:
      - ${CONFIG}/tautulli:/config
      - ${CONFIG}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/logs
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

  teamspeak: #9987
    image: teamspeak
    container_name: teamspeak
    network_mode: host
    volumes:
      - ${CONFIG}/teamspeak:/var/ts3server/
    environment:
      - TS3SERVER_LICENSE=accept

    restart: unless-stopped

  etesync: #3735
    image: victorrds/etesync
    container_name: etesync
    environment:
      - SUPER_USER=admin
    volumes:
      - ${DATA}/etesync:/data
    restart: unless-stopped

  ombi: #3579
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/ombi:/config
    restart: unless-stopped

  sftp:
    image: atmoz/sftp
    volumes:
        - ${DATA}/media:/home/antares/media
        - ${CONFIG}/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
        - ${CONFIG}/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
        - ${CONFIG}/sftp/users.conf:/etc/sftp/users.conf:ro
        - ${CONFIG}/sftp/ssh_authorized_keys:/home/antares/.ssh/keys/:ro
    ports:
        - "2222:22"
    restart: unless-stopped
